import {ask} from './dialog.js';
import {connect} from './demo-repository.js';import {adminSession} from './demo-session.js';import {labels} from './workflow.js';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const root=document.querySelector('#app'),session=adminSession();
async function start(){const {repo}=await connect();let rows=[],search='',filter='pending',order='desc';
 root.innerHTML=`<p class="eyebrow">Area Cilentomania · Demo</p><div class="row"><h1>Le schede da accompagnare online</h1><a class="button" href="./">Area Operatori</a></div><p class="muted">Controlla gli invii, approva i contenuti o indica all’operatore cosa migliorare.</p><section class="panel filters"><label class="field">Cerca scheda o operatore<input id="search" type="search" placeholder="Nome struttura o organizzazione"></label><label class="field">Mostra<select id="filter"><option value="pending">In attesa di approvazione</option><option value="all">Tutti gli invii</option><option value="approved">Approvati</option><option value="changes_requested">Modifiche richieste</option></select></label><label class="field">Ordina per data<select id="order"><option value="desc">Più recenti</option><option value="asc">Meno recenti</option></select></label></section><p role="status" class="status" aria-live="polite"></p><div class="queue"></div><details class="simulator"><summary>Simulazione locale degli stati di pubblicazione</summary><p class="footnote">Solo per provare il modello. Non pubblica né sospende pagine sul sito reale.</p><div id="simulations"></div></details>`;
 const message=text=>root.querySelector('[role=status]').textContent=text;
 function draw(){const shown=rows.filter(r=>(filter==='all'||filter==='pending'&&['submitted','in_review'].includes(r.status)||r.status===filter)&&`${r.name} ${r.organization}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>order==='desc'?b.updatedAt.localeCompare(a.updatedAt):a.updatedAt.localeCompare(b.updatedAt));
  root.querySelector('.queue').innerHTML=shown.map(r=>`<article class="panel queue-card"><div class="row"><h2>${e(r.name)}</h2><span class="badge">${e(labels[r.status])}</span></div><p>Operatore: <strong>${e(r.organization)}</strong><br>Ultima modifica: ${new Date(r.updatedAt).toLocaleString('it-IT')}</p>${r.feedback?`<p class="notice">${e(r.feedback)}</p>`:''}<div class="actions"><a class="button" href="anteprima.html?admin=1&scheda=${encodeURIComponent(r.profileId)}&invio=${encodeURIComponent(r.id)}">Visualizza</a>${['submitted','in_review'].includes(r.status)?`<button data-action="in_review" data-id="${e(r.id)}" ${r.status==='in_review'?'disabled':''}>Avvia revisione</button><button class="primary" data-action="approved" data-id="${e(r.id)}">Approva</button><button data-action="changes_requested" data-id="${e(r.id)}">Richiedi modifiche</button>`:''}</div></article>`).join('')||'<div class="panel empty"><h2>Nessun invio da mostrare</h2><p>Gli invii demo dell’Area Operatori compariranno qui.</p></div>';
  root.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const row=rows.find(r=>r.id===b.dataset.id);let feedback='';if(b.dataset.action==='changes_requested'){feedback=await ask('Quali modifiche chiedi all’operatore?',{feedback:true});if(feedback===null)return;}b.disabled=true;try{await repo.review(session,{id:row.profileId,version:row.version,revisionId:row.id,target:b.dataset.action,feedback});await refresh();message('Esito salvato nella demo. Il sito pubblico resta invariato.');}catch(err){message(err.message);b.disabled=false;}});
 }
 async function refresh(){rows=await repo.queue(session);draw();const profiles=await repo.list(session);root.querySelector('#simulations').innerHTML=profiles.map(p=>`<div class="row"><span>${e(p.name)} · ${e(labels[p.publicationStatus])}</span><div class="actions">${p.revisions.some(r=>r.status==='approved')?`<button data-sim="published" data-profile="${e(p.id)}">Simula pubblicazione</button>`:''}${p.publicationStatus==='published'?`<button data-sim="suspended" data-profile="${e(p.id)}">Simula sospensione</button>`:p.publicationStatus==='suspended'?`<button data-sim="published" data-profile="${e(p.id)}">Simula riattivazione</button>`:''}</div></div>`).join('');root.querySelectorAll('[data-sim]').forEach(b=>b.onclick=async()=>{const p=profiles.find(p=>p.id===b.dataset.profile);if(!await ask('Applicare lo stato soltanto alla demo locale?'))return;try{await repo.simulate(session,{id:p.id,version:p.version,target:b.dataset.sim,revisionId:p.revisions.find(r=>r.status==='approved')?.id});await refresh();message('Stato simulato localmente. Nessuna pubblicazione reale.');}catch(err){message(err.message);}});}
 root.querySelector('#search').oninput=event=>{search=event.target.value;draw();};root.querySelector('#filter').onchange=event=>{filter=event.target.value;draw();};root.querySelector('#order').onchange=event=>{order=event.target.value;draw();};
 window.addEventListener('focus',()=>refresh().catch(err=>message(err.message)));await refresh();
}start().catch(err=>root.textContent=err.message);
