import {connect} from './demo-repository.js';
import {current,login,logout} from './demo-session.js';
import {labels} from './workflow.js';
import {openEditor} from './editor.js';
export const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const typeLabels={accommodation:'Struttura ricettiva',restaurant:'Dove mangiare',experience:'Esperienza',event:'Evento',service:'Servizio',itinerary:'Itinerario'};
const root=document.querySelector('#app');
async function start(){
 const {repo,seed}=await connect();let session=current();const publicId=p=>p.publicPageId||seed.profiles.find(item=>item.id===p.id)?.publicPageId;
 const status=msg=>{root.querySelector('[role=status]').textContent=msg;};
 function access(){root.innerHTML=`<section class="panel login"><div class="welcome"><p class="eyebrow">Cilentomania HUB</p><h1>La tua ospitalità,<br>in buone mani.</h1><p>Uno spazio semplice per raccontare la tua attività e tenere aggiornata la tua scheda.</p></div><form id="login"><p class="eyebrow">Area Operatori</p><h2>Benvenuto</h2><label class="field">Email<input name="email" type="email" autocomplete="off" required value="anna@example.test"></label><label class="field">Password<input name="password" type="password" autocomplete="off" required placeholder="Password demo: demo"></label><button class="primary" type="submit">Accedi</button><button class="text-button" type="button" id="recover">Recupera password</button><p class="status" role="status" aria-live="polite"></p><details><summary>Account per provare la demo</summary><p class="footnote">Anna e Luca: stessa organizzazione.<br>anna@example.test · luca@example.test<br>Marta: altra organizzazione.<br>marta@example.test<br>Password per tutti: <strong>demo</strong></p></details></form></section>`;root.querySelector('#recover').onclick=()=>status('Il recupero password non è attivo nella demo. Nessuna email verrà inviata.');root.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);session=login(seed,f.get('email'),f.get('password'));await dashboard();}catch(err){status(err.message);}};}
 async function dashboard(){
  const items=await repo.list(session);const orgs=seed.memberships.filter(m=>m.userId===session.userId).map(m=>seed.organizations.find(o=>o.id===m.organizationId)?.name);
  root.innerHTML=`<div class="row"><div><p class="eyebrow">Il tuo spazio Cilentomania</p><h1>Benvenuto, ${escape(orgs.join(' · '))}</h1></div><button id="logout">Esci</button></div><p class="muted">Racconta la tua attività. Le modifiche saranno controllate da Cilentomania prima della pubblicazione.</p><h2>Le mie schede</h2><div class="cards">${items.map(p=>`<article class="panel profile-card"><img src="../images/comuni/castellabate-card.jpg" alt="Paesaggio illustrativo del Cilento"><div class="card-body"><div class="row"><span class="badge">Scheda: ${escape(labels[p.publicationStatus])}</span><span class="badge demo">DEMO</span></div><h2 style="margin-top:18px">${escape(p.workingRevision.content.nome)}</h2><p class="muted">${escape(typeLabels[p.type]||'Scheda')} · ${escape(p.workingRevision.content.localita)}</p><p>${escape(labels[p.workingRevision.status])}</p>${p.workingRevision.feedback?`<p class="notice">${escape(p.workingRevision.feedback)}</p>`:''}<div class="actions"><button class="primary" data-edit="${escape(p.id)}">Modifica scheda</button>${p.publishedVersion&&publicId(p)?`<a class="button" href="../?scheda=${encodeURIComponent(publicId(p))}" target="_blank" rel="noopener">Visualizza pagina pubblica ↗</a>`:''}</div><section class="subscription" style="margin-top:28px"><h3>Il mio abbonamento</h3><dl>${['Stato','Piano','Decorrenza','Scadenza'].map(k=>`<div><dt>${k}</dt><dd>Non ancora disponibile</dd></div>`).join('')}</dl></section></div></article>`).join('')||'<p>Nessuna scheda associata.</p>'}</div><p class="status" role="status"></p><p class="footnote">Demo locale: i dati non vengono condivisi con altri dispositivi. Le schede pubblicate sul sito restano invariate.</p>`;
  root.querySelector('#logout').onclick=()=>{logout();session=null;history.replaceState(null,'',location.pathname);access();};root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor({root,repo,session,id:b.dataset.edit,back:dashboard}));
 }
 if(session){try{const id=new URLSearchParams(location.search).get('scheda');if(id)await openEditor({root,repo,session,id,back:dashboard});else await dashboard();}catch(err){access();status(err.message);}}else access();
}
start().catch(e=>{root.textContent='Impossibile aprire l’area: '+e.message;});
