import {ask} from './dialog.js';
import {sections} from './model.js';import {labels} from './workflow.js';import {addFiles,mediaUrl,release} from './media.js';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tabs={informazioni:'Informazioni',foto:'Foto',contatti:'Contatti',caratteristiche:'Caratteristiche',servizi:'Servizi',posizione:'Posizione'};
export async function openEditor({root,repo,session,id,back}){
 let profile=await repo.get(session,id),draft=structuredClone(profile.workingRevision.content),media=structuredClone(profile.workingRevision.media),tab='informazioni',dirty=false,urls=[],busy=false;
 const [dictionary,townData]=await Promise.all(['../i18n/it.json','../data/comuni.json'].map(url=>fetch(url).then(r=>r.json())));
 const towns=Array.isArray(townData.municipalities)?townData.municipalities:townData.municipalities.value;
 const slug=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 const locked=()=>!['draft','changes_requested','approved','published'].includes(profile.workingRevision.status);
 const unload=event=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',unload);
 const message=(text,error=false)=>{const box=root.querySelector('[role=status]');box.textContent=text;box.classList.toggle('error',error);};
 function collect(){root.querySelectorAll('[data-field]').forEach(input=>{const key=input.dataset.field,type=input.dataset.type;draft[key]=type==='tri'?(input.value===''?null:input.value==='true'):['number','coordinate'].includes(type)?(input.value===''?null:Number(input.value)):type==='list'?input.value.split('\n').map(s=>s.trim()).filter(Boolean):input.value;});if(tab==='servizi')draft.serviceCodes=[...root.querySelectorAll('[data-service]:checked')].map(i=>i.dataset.service);if(tab==='foto')root.querySelectorAll('[data-media-field]').forEach(input=>{media[Number(input.dataset.index)][input.dataset.mediaField]=input.value;});}
 function field([key,label,type='text']){const v=draft[key];let input;
  if(type==='tri')input=`<select data-field="${key}" data-type="tri">${[['','Non specificato'],['true','Sì'],['false','No']].map(([value,text])=>`<option value="${value}" ${String(v??'')===value?'selected':''}>${text}</option>`).join('')}</select>`;
  else if(type==='municipality')input=`<select data-field="${key}"><option value="">Non specificato</option>${towns.map(name=>`<option value="${slug(name)}" ${v===slug(name)?'selected':''}>${e(name)}</option>`).join('')}</select>`;
  else if(['textarea','list'].includes(type))input=`<textarea data-field="${key}" data-type="${type}" maxlength="12000">${e(type==='list'?(v||[]).join('\n'):v)}</textarea>`;
  else input=`<input data-field="${key}" data-type="${type}" type="${type==='coordinate'?'number':type}" ${type==='coordinate'?'step="any"':type==='number'?'min="0" step="1"':''} value="${e(v)}" maxlength="2000">`;
  return `<label class="field">${e(label)}${input}</label>`;
 }
 function render(){release(urls);urls=[];
  root.innerHTML=`<div class="row"><button id="back">← Le mie schede</button><span class="badge demo">Modifiche locali · DEMO</span></div><h1 style="margin-top:24px">${e(draft.nome)}</h1><p class="muted">${e(labels[profile.workingRevision.status])}</p>${profile.workingRevision.feedback?`<p class="notice">${e(profile.workingRevision.feedback)}</p>`:''}${locked()?'<p class="notice">Le modifiche sono in attesa di Cilentomania. Puoi consultarle e aprire l’anteprima.</p>':''}<div class="editor"><nav class="tabs" aria-label="Sezioni della scheda">${Object.entries(tabs).map(([key,label])=>`<button data-tab="${key}" aria-current="${tab===key}">${label}</button>`).join('')}</nav><div class="editor-content"><section class="panel"><h2>${tabs[tab]}</h2><form id="fields"><fieldset ${locked()?'disabled':''} style="border:0;padding:0;margin:0;min-width:0">${tab==='foto'?photos():tab==='servizi'?`<p class="muted">Seleziona i servizi disponibili. Una casella non selezionata indica che il servizio non è specificato.</p><div class="grid">${globalThis.OperatorProfileModel.SERVICE_CODES.map(code=>`<label class="check"><input type="checkbox" data-service="${code}" ${(draft.serviceCodes||[]).includes(code)?'checked':''}>${e(dictionary.operatorProfile.serviceLabels[code])}</label>`).join('')}</div>`:`<div class="grid">${sections[tab].map(field).join('')}</div>`}${tab==='posizione'?'<p class="muted">La mappa usa le coordinate inserite. Apri Anteprima per controllare la posizione.</p>':''}</fieldset></form></section><p class="status notice" role="status" aria-live="polite">${dirty?'Modifiche non ancora salvate.':profile.workingRevision.updatedAt?'Ultimo salvataggio: '+new Date(profile.workingRevision.updatedAt).toLocaleString('it-IT'):'Nessuna modifica da salvare.'}</p><div class="editor-actions"><button id="save" ${locked()?'disabled':''}>Salva bozza</button><button id="preview">Anteprima</button><button class="primary" id="submit" ${locked()?'disabled':''}>Invia a Cilentomania</button></div><p class="footnote">Salvataggio solo in questo browser. L’invio non contatta realmente Cilentomania e non modifica il sito pubblico.</p></div></div>`;
  root.querySelector('#fields').onsubmit=event=>event.preventDefault();root.querySelector('#fields').oninput=()=>{dirty=true;message('Modifiche non ancora salvate.');};
  root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{collect();tab=b.dataset.tab;render();});
  root.querySelector('#back').onclick=async()=>{if(dirty&&!await ask('Hai modifiche non salvate. Vuoi uscire senza salvarle?'))return;release(urls);window.removeEventListener('beforeunload',unload);history.replaceState(null,'',location.pathname);back();};
  root.querySelector('#save').onclick=()=>action('save');root.querySelector('#preview').onclick=()=>action('preview');root.querySelector('#submit').onclick=()=>action('submit');
  if(tab==='foto'){
   root.querySelector('#files').onchange=async ev=>{try{collect();media=await addFiles(ev.target.files,media);dirty=true;render();message('Foto aggiunte. Salva per conservarle.');}catch(err){message(err.message,true);}};
   root.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{collect();const i=+b.dataset.index,j=i+Number(b.dataset.move);[media[i],media[j]]=[media[j],media[i]];dirty=true;render();});
   root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{collect();media.splice(+b.dataset.remove,1);dirty=true;render();});
  }
 }
 function photos(){return `<p class="muted">Logo, copertina e immagini della struttura. JPG, PNG o WebP, massimo 5 MB ciascuna. I paesaggi iniziali sono illustrativi.</p><label class="field">Aggiungi fotografie<input id="files" type="file" accept="image/jpeg,image/png,image/webp" multiple></label>${media.map((m,i)=>{const url=mediaUrl(m);urls.push(url);return `<article class="media-card"><img src="${e(url)}" alt="${e(m.alt)}"><div class="grid"><label class="field">Utilizzo<select data-media-field="kind" data-index="${i}">${[['logo','Logo'],['cover','Copertina'],['gallery','Gallery']].map(([v,l])=>`<option value="${v}" ${v===m.kind?'selected':''}>${l}</option>`).join('')}</select></label><label class="field">Didascalia<input data-media-field="caption" data-index="${i}" value="${e(m.caption)}"></label><label class="field">Descrizione dell’immagine (accessibilità)<input data-media-field="alt" data-index="${i}" value="${e(m.alt)}"></label></div><div class="actions"><button type="button" data-index="${i}" data-move="-1" ${i===0?'disabled':''} aria-label="Sposta prima la foto ${i+1}">↑ Prima</button><button type="button" data-index="${i}" data-move="1" ${i===media.length-1?'disabled':''} aria-label="Sposta dopo la foto ${i+1}">↓ Dopo</button><button type="button" data-remove="${i}" aria-label="Rimuovi la foto ${i+1}">Rimuovi</button></div></article>`;}).join('')}`;}
 async function action(kind){if(busy)return;busy=true;root.querySelectorAll('.editor-actions button').forEach(b=>b.disabled=true);
  try{collect();if(!root.querySelector('#fields').reportValidity())return;
   if(kind==='submit'&&!await ask('Inviare le modifiche alla coda demo di Cilentomania? Il sito pubblico resterà invariato.'))return;
   if(!locked()&&(dirty||kind==='save'||kind==='submit')){profile=await repo.save(session,{id,version:profile.version,patch:draft,media});dirty=false;}
   if(kind==='submit')profile=await repo.submit(session,{id,version:profile.version});
   if(kind==='preview'){window.removeEventListener('beforeunload',unload);location.href='anteprima.html?scheda='+encodeURIComponent(id);return;}
   render();message(kind==='submit'?'Modifiche inviate alla coda demo. Nessuna modifica al sito pubblico.':'Bozza salvata in questo browser.');
  }catch(err){message(err.message,true);}finally{busy=false;root.querySelectorAll('.editor-actions button').forEach(b=>b.disabled=locked()&&b.id!=='preview');}
 }
 render();
}
