import {contentType} from './content-types.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const display=value=>value===null||value===undefined||value===''||(Array.isArray(value)&&!value.length)?'Non specificato':typeof value==='boolean'?(value?'Sì':'No'):Array.isArray(value)?value.join(' · '):String(value);
// Demo-only restaurant preview. Public dining and its renderer stay untouched.
export function renderRestaurant(root,content,media,municipality,back,{demo=true}={}) {
 const definition=contentType('restaurant'),photos=media.filter(m=>m.kind!=='logo'),cover=photos.find(m=>m.kind==='cover')||photos[0],logo=media.find(m=>m.kind==='logo');
 root.innerHTML=`<article class="restaurant-preview"><div class="row"><a class="button" href="${escape(back)}">← Torna alla scheda</a><span class="badge demo">${demo?'DEMO · Anteprima':'Bozza · Non pubblicata'}</span></div>
 <header class="restaurant-hero">${cover?`<img src="${escape(cover.url)}" alt="${escape(cover.alt)}" style="object-position:${Number(cover.focalX??50)}% ${Number(cover.focalY??50)}%">`:''}<div>${logo?`<img class="restaurant-logo" src="${escape(logo.url)}" alt="Logo del locale">`:''}<p>${escape(content.categoria||'Ristorante')} · ${escape(municipality)}</p><h1>${escape(content.nome)}</h1><p>${escape(content.claim)}</p><button id="all-restaurant-photos" ${photos.length?'':'disabled'}>Tutte le foto (${photos.length})</button></div></header>
 <div class="restaurant-cta" aria-label="Contatti dimostrativi">${['Chiama','WhatsApp','Indicazioni','Prenota'].map(label=>`<button disabled>${label}</button>`).join('')}</div><p class="footnote">${demo?'Esempio dimostrativo: fotografie illustrative e contatti non attivi.':'Anteprima privata: i pulsanti di contatto sono disattivati.'}</p>
 <section><p class="eyebrow">A tavola nel Cilento</p><h2>Il nostro locale</h2><p class="restaurant-description">${escape(content.descrizione_completa||content.descrizione_breve)}</p></section>
 <section><h2>Cucina e informazioni</h2><dl class="restaurant-details">${definition.sections.caratteristiche.map(([key,label])=>`<div><dt>${escape(label.replace(/ \(.*\)/,''))}</dt><dd>${escape(display(content[key]))}</dd></div>`).join('')}</dl></section>
 <section><h2>Servizi</h2><div class="restaurant-services">${(content.serviceCodes||[]).filter(code=>Object.hasOwn(definition.services,code)).map(code=>`<span>${escape(definition.services[code])}</span>`).join('')||'<p>Non specificati</p>'}</div></section>
 <section><h2>Dove siamo</h2><p>${escape(municipality)}${content.localita?' · '+escape(content.localita):''}</p><p>${escape(content.indirizzo||'Indirizzo non specificato')}</p><p class="notice">${demo?'La posizione di questo locale è dimostrativa. La mappa sarà disponibile con dati verificati.':'Mappa in preparazione: controlla indirizzo e coordinate nel modulo Posizione.'}</p></section>
 <dialog class="restaurant-gallery"><button id="close-restaurant-gallery">Chiudi ×</button><p class="footnote">${demo?'Fotografie illustrative · DEMO':'Foto della bozza'}</p><div>${photos.map(m=>`<figure><img loading="lazy" src="${escape(m.url)}" alt="${escape(m.alt)}"><figcaption>${escape(m.caption||m.alt)}</figcaption></figure>`).join('')}</div></dialog></article>`;
 const dialog=root.querySelector('dialog');root.querySelector('#all-restaurant-photos').onclick=()=>dialog.showModal();root.querySelector('#close-restaurant-gallery').onclick=()=>dialog.close();
}
